import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "./globals.css";

export const inter = Inter({
  variable: "--font-inter",
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
});

export const geistSans = Geist({
  variable: "--font-geist-Sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${inter.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
